package stt

var allowedAudioCodecs = map[InputAudioCodec]bool{
	"wav":       true,
	"x-wav":     true,
	"wave":      true,
	"mp3":       true,
	"mpeg":      true,
	"mpeg3":     true,
	"x-mpeg-3":  true,
	"x-mp3":     true,
	"x-aac":     true,
	"aac":       true,
	"aiff":      true,
	"x-aiff":    true,
	"ogg":       true,
	"opus":      true,
	"flac":      true,
	"x-flac":    true,
	"mp4":       true,
	"x-m4a":     true,
	"amr":       true,
	"x-ms-wma":  true,
	"webm":      true,
	"pcm_s16le": true,
	"pcm_l16":   true,
	"pcm_raw":   true,
}
